"""Criacao inicial das tabelas

Revision ID: 26fe78687035
Revises: 
Create Date: 2025-10-18 23:05:53.375957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fe78687035'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tombo', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('finalidade', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('localizacao', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem_filename', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coordenador_name', sa.String(length=100), nullable=True),
    sa.Column('coordenador_email', sa.String(length=100), nullable=True),
    sa.Column('bolsista_name', sa.String(length=100), nullable=True),
    sa.Column('bolsista_email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('sistema_operacional', sa.String(length=200), nullable=True),
    sa.Column('softwares_instalados', sa.Text(), nullable=True),
    sa.Column('licencas', sa.String(length=255), nullable=True),
    sa.Column('limpeza_fisica_data', sa.Date(), nullable=True),
    sa.Column('ultima_formatacao_data', sa.Date(), nullable=True),
    sa.Column('responsavel_formatacao', sa.String(length=80), nullable=True),
    sa.Column('imagem_filename', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('report')
    op.drop_table('machine')
    op.drop_table('lab_info')
    op.drop_table('equipment')
    # ### end Alembic commands ###
